- name: Provision AWS EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files:
    - vars/ec2_tags.yml
    - vars/ec2_config.yml

  tasks:
  - include_tasks: tasks/create_security_groups.yml
  - include_tasks: tasks/create_ec2_instances.yml